### ISSUE TITLE
wrong install cmd on README.md

### ISSUE THREAD

**Issue by onel0p3z** [FlexShopper/eslint-config#8]
this is the way `npm install --save-dev flexshopper/eslint-config`

**Comment by italoacasas** [comment]
the correct way to install a package from Github is using the `url`

`npm install --save-dev https://github.com/flexshopper/eslint-config`

https://github.com/FlexShopper/eslint-config/pull/9 should be fix this problem

**Comment by onel0p3z** [comment]
@italoacasas you can also the issue number on a commits that referencees and closes it. Also please consider this from the [npm docs](https://docs.npmjs.com/cli/install):
> Note: if you do not include the @-symbol on your scope name, npm will interpret this as a **GitHub repository instead**, see below. Scopes names must also be followed by a slash.

> Examples:
```
    npm install sax --save
    npm install githubname/reponame
    npm install @myorg/privatepackage
    npm install node-tap --save-dev
    npm install dtrace-provider --save-optional
    npm install readable-stream --save --save-exact
```
